### ISSUE TITLE
[RFC] Discuss possibility of adding `toByteString` and `toLByteString` functions

### ISSUE THREAD

**Issue by chshersh** [kowainik/relude#108]
Sometimes useful. Having `encodeUtf8` and `decodeUtf8` names is nice because it hints to the implementation. But sometimes you just want call functions with meaningful names, especially when we have `toString` and `toText`.

Regarding `decodeUtf8` — we can function like:

* `unsafeFrom[L]ByteString`

as synonym to `decodeUtf8`.

What do others think?

**Comment by kahlil29** [comment]
@ChShersh Have you checked out/used the function `toS` from the library `Data.String.Conv`
It's in package `string-conv` .
I have no clue how heavy this package is or what the performance or compile-time effects are but we used to use it by default at Vacation Labs (my previous company) for all `String <-> Text <-> ByteString` conversions and more and it usually works very well for me. 
It saves me a lot of headaches(not really 😛, I guess I'm just lazy) of having to find the exact function for the exact 2 types I'm converting to/from for trivial conversions when all I want is to solve the compiler error(s) and make my program compile. 

Just thought I'd put this out here, hope it's relevant to this discussion.

**Comment by ChShersh** [comment]
@kahlil29 This is actually how it was initially done and how it's done in `protolude`:

* https://github.com/sdiehl/protolude/blob/master/src/Protolude/Conv.hs#L30-L31

But I personally prefer solution with multiple typeclasses because it's better for type inference. Especially when you can polymorphic `show` function. Also, `ByteString` is somewhat special case because there're many ways to convert to `ByteString` and I think that it's a good idea to specify how we convert to `ByteString`.

**Comment by kahlil29** [comment]
Yes I think I get your point. 
To refer back to your initial comment, you want to name it `unsafeFrom[L]ByteString` because `decodeUtf8` throws an exception when it encounters invalid characters?

**Comment by ChShersh** [comment]
@kahlil29 Yes, `unsafe` prefix is for things that can throw `error` in runtime and you take risk by calling this function. So you don't have proof for GHC that this function will always work, but if you use it correctly then you're good. I don't want to name function that returns `Either` as `fromByteString` because all `to/from` functions doesn't return `Either` and it will confuse users a lot when some functions return `Either` and some - don't.

**Comment by tysonzero** [comment]
@chshersh Personally I think `unsafe` is a bit overkill for partiality, and should be reserved for segfaulty/type-unsafe/UB stuff like `unsafePerformIO` and `unsafeCoerce`. I wish `!` could be used like `'` in symbols, as then I would suggest a `!` suffix for partial functions.

**Comment by chshersh** [comment]
@tysonzero I think that `unsafe` prefix is completely fine for partiality. Especially when having nice stack traces is still not an easy job and catching errors from pure code is not something you're supposed to do in Haskell. I often use `unsafe` when I have a data type with the hidden constructor and exported smart constructor (like a hash of the password), but sometimes I need to construct raw value (e.g. for tests). I don't want this `unsafePasswordHash` to be in the production codebase, so having `unsafe` prefix is a strong signal to notice such things during code review.

**Comment by chshersh** [comment]
`encodeUtf8` becomes standard for this case. And there's already another way to improve the situation: write better docs and use custom type errors to guide users of the library. So I'm closing this issue as `wontfix`.
