### ISSUE TITLE
Consider adding `witherable` to `relude`

### ISSUE THREAD

**Issue by tysonzero** [kowainik/relude#113]
The function I personally hide most often from `Prelude` is `filter`, so that I can import `filter` and friends from `Data.Witherable` and filter various other containers.

So my suggestion is to consider adding `witherable` to `relude` and exporting many of those functions instead of the equivalent list-only `Prelude` functions.

**Comment by ChShersh** [comment]
@tysonzero Thank you for the suggestion! I like `witherable` and I like abstractions behind this package. I would appreciate having polymorphic `filter` and `mapMaybe` function that work at least for `[a]` and `NonEmpty a`. Unfortunately, I don't think that we can add `Witherable` to the dependencies of the `relude`. I've looked at dependency graphs for the `relude` and for the `witherable` packages and here they are:

### relude

![relude](https://user-images.githubusercontent.com/4276606/47403650-d688b480-d77c-11e8-939b-bf9eb4798b78.png)

### witherable

![witherable](https://user-images.githubusercontent.com/4276606/47403673-edc7a200-d77c-11e8-9b3d-20775f624f21.png)

So, adding `witherable` to the dependencies of the `relude` adds the following dependencies:

1. `witherable` itself
2. `vector`
3. `primitive`
4. `base-orphans`

I really want for the `relude` to be relatively lightweight package that contains only basic and most common staff. You can see from this graph that some dependencies are bundled with GHC itself and all new dependencies that `witherable` brings are not bundled with GHC, so they are really _extra_ dependencies. I would like for `witherable` to depend only on basic packages, or, even more, move `Witherable` to the `base` at some point. The only solution I can see now is to reimplement `Witherable` in the `Relude.Extra.Witherable` keeping copyright notice.

**Comment by tysonzero** [comment]
> The only solution I can see now is to reimplement Witherable in the Relude.Extra.Witherable

Hmm, reimplimenting classes is IMO worse than just leaving it out, as then various libraries that add witherable instances will not be compatible.

The rest of what you said makes sense, although it is a shame.

I just wish the orphans situation with GHC/Haskell could be figured out (blessed modules / packages maybe?) so that various abstraction libraries like `witherable` could have absolutely no dependencies besides on other abstractions they directly build on.

**Comment by ChShersh** [comment]
> as then various libraries that add witherable instances will not be compatible.

Yeah, that's unfortunate. Similar thing with reimplementing data types (you still need to add instances from foreign libraries), but to me if feels that data types are easier to reimplement.

I feel that `witherable` should depend only on `base` and then other packages like `vector` can depend on `witherable`. It's much easier to depend on lightweight package rather than on heavy one. And then we can say something: _Hey, look, there're 100 packages depend on very useful and light abstraction called `Witherable`, can we include it to `base`?_ `Contravariant` is already in `base`, I think this can happen to other typeclasses as well. 

I personally don't mind putting things like `Contravariant`, `Divisible`, `Decidable`, `Profunctor`, `Comonad`, `Tagged`, `Witherable` and other stuff. They look idiomatic enough.

I think what can be done to move things in this positive direction: open issue at `witherable` package and discuss possibility to split this package into `witherable` and `witherable-instances` (or `witherable-orphans`).

**Comment by janpath** [comment]
Well `base-orphans` is really small and will always be empty on the newest version of `base`.  Actually exporting it's instances in `Relude` would be a cheap way to improve backwards compatibility a bit. `vector` is a really common package as far as I'm concerned and if we depend on it anyway, I think would be reasonable to export `Vector` in `Relude` as well.

Furthermore `witherable` would have to be added to the Haskell Platform in order to inverse the dependencies of `witherable` on `vector` and `unordered-containers`, so that is rather unlikely to happen. Splitting `witherable` into `witherable`, `witherable-instances` and `witherable-class` would be possible but doing that because of `vector` and `unordered-containers` could be a hard sell for the added complexity.

**Comment by chshersh** [comment]
@janpath Despite being small or famous, it is still an extra dependency. Alternatives preludes should be used only in applications, not libraries. And I think it's quite common to write applications without using `witherable` or `vector` (also, in my experience `vector` actually takes some time to build). I don't want to force users of `relude` to depend on many libraries they don't actually use. And I don't want to have an additional quite expensive maintenance cost of having another non-boot package in dependencies.

One of the `relude` goals are to be minimal and don't force particular abstractions and implementations if there are alternatives. For example, instead of `vector`, you can also use `array` or `primitive` packages and sometimes it's a good idea to do so. `unordered-containers` don't have an alternative, and this package is the de-facto standard for `HashMap`s in Haskell, which is a vital data structure for many applications.

**Comment by chshersh** [comment]
I am closing this issue as `wontfix` since it conflicts with the goals for this package.
