### ISSUE TITLE
Add `traverseToSnd` and friends to `Relude.Extra.Tuple`

### ISSUE THREAD

**Issue by josephcsible** [kowainik/relude#144]
I think `traverse` analogues to the `map` functions in `Relude.Extra.Tuple` would be useful:

```haskell
traverseToFst :: Functor t => (a -> t b) -> a -> t (b, a)
traverseToFst f a = flip (,) a <$> f a

traverseToSnd ::  Functor t => (a -> t b) -> a -> t (a, b)
traverseToSnd f a = (,) a <$> f a

traverseBoth :: Applicative t => (a -> t b) -> (a, a) -> t (b, b)
traverseBoth f (a1, a2) = (,) <$> f a1 <*> f a2
```

(No analogue of `dupe`, at least for now, because there'd be ambiguity over whether it worked like `\a -> join (,) <$> a` or like `\a -> (,) <$> a <*> a`, and I'm not sure which would be better.)

The use case that inspired this was a function (`FilePath -> IO (FilePath, String)`) that takes a filename, and returns a pair of the name and the contents. With this proposal, such a function would simply be `traverseToSnd readFile`.

If this idea is acceptable, I'll make a PR that adds it along with hlint rules and tests.

**Comment by ChShersh** [comment]
@josephcsible Thanks for your proposal! The idea looks good to me, I see how these functions can be useful :thinking: So you're welcome to open PR, I appreciate your contribution :+1: 

Though I have several comments regarding this issue. First, I think `traverseToFst` and `traverseToSnd` functions can be written a little bit nicer using `-XTupleSections` extension:

```haskell
traverseToFst f a = (,a) <$> f a
traverseToSnd f a = (a,) <$> f a
```

Second, regarding `traverseDupe`: I think that the implementation via `join (,) <$> a` (or simply just `dupe <$> a`) is better because it's less surprising in some sense. Generally you don't want to duplicate effects twice, this can lead to some unexpected behavior. Take function like `getLine` for example. I can see why you might want to read single line of text and return two copies of this line (this behavior is provided using `join` implementation). But you probably don't want just call `getLine` twice, from `dupe` functions I expect to return the same value. If you need to call some action twice, then just use `replicateM 2` or something like that. At the same time, `traverseDupe a` is not really shorter than `dupe <$> a` :slightly_smiling_face: Does this makes sense for you as well?

Regarding tests: I think it will be okay to have just example tests using `doctest`. You commend regarding functions that have type like `FilePath -> IO (FilePath, String)` seems valuable, I think this text also can be added to the documentation :books: 

Regarding HLint rules: currently we don't have any HLint rules for `Relude.Extra.*` functions (see issue #136). You probably will be the first person to add such rules. That's why you don't have any examples. But I think that rules for things from `Relude.Extra.*` namespace should be `hints` instead of warnings, so  use `hintNote` function:

https://github.com/kowainik/relude/blob/0d71a4d4d772e737deee947445a1f77afd06c6bc/hlint/hlint.dhall#L7

And also I think that all HLint rules for `Extra` should go to the end of `hlint/hlint.dhall` file under `-- Extra` section.
