### ISSUE TITLE
Rename and deprecate `mapToFst/Snd`

### ISSUE THREAD

**Issue by vrom911** [kowainik/relude#196]
In https://github.com/kowainik/relude/pull/194 I've noticed that functions `mapToFst`/`mapToSnd`/`mapBoth` have a bit misleading name. Check out the type:

```haskell
mapToFst :: (a -> b) -> a -> (b, a)
```

when I would expect it to have the following type:

```haskell
mapToFst :: (a -> b) -> f a -> f (b, a)
```

(which is exactly what was needed in the mentioned PR, and we used `map (mapToFst f)` in there).

I also understand, that this is breaking change and I am not sure if it worth it. Need to thing about renaming or deprecating process a bit harder.

Anyway, at least adding functions which would actually map the containers is also a possible solution for the issue. I would really appreciate the discussion of this problem.

cc @kowainik/dev

**Comment by chshersh** [comment]
@vrom911 I think renaming to less confusing names worth it in the long term. Regarding deprecation process: we can use the process described in my blog post (which includes multi-stage process with `DEPRECATED` pragmas and custom type errors):

* https://kodimensional.dev/type-errors#deprecation-better-migration-guide

Regarding `mapBoth`: we have a separate issue #174. Probably instead of only generalisation we can also rename the function to `bimapBoth` and have `bimapBothF` in the spirit of other functions in the `Relude.Extra.Bifunctor` module.

We can introduce new functions first and deprecate the old ones:

```haskell
??? :: (a -> b) -> a -> (b, a)
fmapToFst :: Functor f => (a -> b) -> f a -> f (b, a)  -- uses ???
```

It's hard to come up with the good name for `mapToFst`... I can propose the following options:

* `withFst`
* `mapKeepFst`/`keepFst`
* `toFst`

What do you think?

**Comment by willbasky** [comment]
Map implicates  some `f`, therefore it is better to abandon it. 
`withFst` i vote from you polling.

**Comment by josephcsible** [comment]
I'm not a fan of renaming. In my mind, it makes sense that `map` in `mapTo*` refers to mapping over the first/second half of the tuple (and similarly for `traverse`). For example, note the following identities:
* `mapToFst f = bimap f id . dup = first f . dup`
* `mapToSnd f = bimap id f . dup = second f . dup = fmap f . dup`
* `mapBoth f = bimap f f`
* `traverseToFst f = bitraverse f pure . dup`
* `traverseToSnd f = bitraverse pure f . dup = traverse f . dup`
* `traverseBoth f = bitraverse f f`

Also, if you did rename the `map*` functions, what would it even make sense to rename the `traverse*` functions too?

**Comment by chshersh** [comment]
I propose the following change:

1. Rename `mapToFst` and `mapToSnd` to `withFst` and `withSnd` correspondingly.
2. Change the type of `mapToFst` (and `mapToSnd`) to the following:

```haskell
fmapToFst :: Functor f => (a -> b) -> f a -> f (b, a)
fmapToSnd :: Functor f => (a -> b) -> f a -> f (a, b)
```
3. Deprecate `mapToFst` and `mapToSnd`.
