### ISSUE TITLE
Data.Foldable.elem isn't actually slow for Set

### ISSUE THREAD

**Issue by googleson78** [kowainik/relude#215]
While it is true that for `HashSet` [only `foldr` is imlemented](https://www.stackage.org/haddock/lts-14.11/unordered-containers-0.2.10.0/src/Data.HashSet.Base.html#line-140), making `elem` inefficient, the same [isn't true](https://www.stackage.org/haddock/lts-9.21/containers-0.5.7.1/src/Data-Set-Base.html#Set) for `Set`, even as far back as 8.0.2 (which is currently the "last supported version" for `relude`).

So I think it would be safe to remove this restrictions for `Set` (?)

It is also worth noting that there is currently a related issue on this topic at `unordered-containers` - https://github.com/tibbe/unordered-containers/issues/222

**Comment by chshersh** [comment]
@googleson78 It is slow. The problem is in fact that it's not possible to implement fast `elem` from `Foldable` for both `Set` and `HashSet` even if you write explicit implementation. Here is explicit implementation of `elem` for `Set`:

```haskell
    elem = go
      where go !_ Tip = False
            go x (Bin _ y l r) = x == y || go x l || go x r
```

This implementation has O(n) time. However, [`member`](https://hackage.haskell.org/package/containers-0.6.2.1/docs/Data-Set.html#v:member) runs in O(log n). Implementing such fast `elem` in `Foldable` for `Set` requires to change the `Foldable` typeclass itself.

**Comment by googleson78** [comment]
Ah, sorry! I'm just very sleepy it seems. :cry:

**Comment by chshersh** [comment]
@googleson78 No worries :slightly_smiling_face:
