### ISSUE TITLE
scan{l,r}1

### ISSUE THREAD

**Issue by argantos** [kowainik/relude#234]
Why are `scanl1` and `scanr1` missing? They are not partial.

**Comment by chshersh** [comment]
@argantos No particular reason. We happen never to use `scan{l,r}[1]` so these functions were not considered for addition at first place. I don't mind adding `scanl1` and `scanr1` to `relude` as well since these functions are already reexported by `relude`. Maybe we can even add `scanl'` as a more efficient version of `scanl`.
