### ISSUE TITLE
`forM` and `for_` are reexported, but `for` is not

### ISSUE THREAD

**Issue by mithrandi** [kowainik/relude#243]
Is this intentional or just an oversight?

**Comment by chshersh** [comment]
`forM` and `for_` are standard names. These functions have similar semantics in different libraries. Hoogle search for the `for` function shows that there are multiple implementations of different types of the `for`. So having `for` in the scope by default without import can be confusing for some users since this name is too ambiguous in the Haskell ecosystem at the moment. And `relude` goals is to be minimal and beginner-friendly. So I don't see a need to export `for`, since we already have `forM`.

**Comment by mithrandi** [comment]
Thanks!

**Comment by janpath** [comment]
I disagree, looking through the results on Hackage to me it seems that `for` from `Traversable` is by far the most widespread use. All other uses are either domain specific (e.g. pipes, blaze) or some niche utility package which defines `for = flip fmap` but has hence deprecated that because it clashes with `for = flip traverse`. There is also a lot of precedence for exporting for by other preludes (e.g. classy-prelude, rio, rebase) and `Control.Lens` also exports `forBy`. Furthermore `for` is very useful:

```haskell
for container \x ->
  ...

-- vs

flip traverse container \x ->
  ...
```

Not having to decide every time whether it's worth it to add an extra import for such widely useful convenience functions is a major reason why I use a custom prelude in the first place.

**Comment by chris-martin** [comment]
> Hoogle search for the for function shows that there are multiple implementations

I tried this with `for`, as well as a few other things that relude re-exports.

- `for` - base, blaze-html, pipes, utility-ht, statistics, streaming, crypto-api, fclabels, clay, yjtools, Agda, netwire, opaleye, linear-base, BNFC, extrapolate, contiguous
- `for_` - base, directory, lucid, mono-traversable, universum, yjtools, reducers, contiguous
- `sequence` - base, vector, conduit, hedgehog, pipes, streaming, dhall, ListLike, explicit-exception, monad-parallel, streamly, vector-sized, foundation, basement, synthesizer-core, matrices
- `replicateM` - base, containers, directory, vector, conduit, pipes, streaming, mono-traversable, monad-parallel, streamly

It does not seem to me that `for` is exceptional in this regard.

**Comment by chris-martin** [comment]
> I don't see a need to export `for`, since we already have `forM`.

Unfortunately, the utility of `forM` is limited by an unnecessary monad constraint which makes it unsuitable for applicatives such as [`Concurrently`](https://hackage.haskell.org/package/async-2.2.4/docs/Control-Concurrent-Async.html#t:Concurrently) and [`Validation`](https://hackage.haskell.org/package/validation-1.1.2/docs/Data-Validation.html).

**Comment by chris-martin** [comment]
The name `for_` doesn't even make sense in the absence of `for`, because the conventional meaning of the trailing underscore is to indicate that something is a value-discarding variant of something else, and at present that something else is missing.

**Comment by chris-martin** [comment]
Some historical context: `for` has been a part of the [`Data.Traversable`](https://downloads.haskell.org/~ghc/6.6/docs/html/libraries/base/Data-Traversable.html) module since its addition in GHC 6.6, released in October 2006.

**Comment by evanrelf** [comment]
Yeah, I'm confused why `for_` is in `relude` but not `for`, since they're related like @chris-martin said.

`for` is better than `forM` because it only requires `Applicative` instead of `Monad`, and it reads a little nicer (like a `for` loop from imperative languages).
