### ISSUE TITLE
Applicative.hs file has commented out code.

### ISSUE THREAD

**Issue by elsanussi-s-mneina** [kowainik/relude#260]
The functions orAlt, orEmpty, eitherA, purer, liftAA2, and (<<*>>) are commented out. It may be good to add a comment explaining why, or putting that code/comment somewhere else to prevent confusion. Is it an unfinished feature that needs to be tested?

**Comment by elsanussi-s-mneina** [comment]
Link to line where commented out code begins:

https://github.com/kowainik/relude/blob/c5a67571a348aa96cfd80bcbd9fde33a49f3570a/src/Relude/Applicative.hs#L53

**Comment by chshersh** [comment]
@elsanussi-s-mneina `relude` is based on `protolude`, and those combinators were initially in `protolude`. They are not used much, so we decided not to expose them to make `relude` more beginner-friendly. So that's why they were commented. Thus being said, we will revisit what we can add to `relude` and remove the comment.

**Comment by elsanussi-s-mneina** [comment]
Thank you, I understand. I have no input on whether they should be exposed. I only think commented out code can confuse developers, especially when there is no explanation. I made two branches for this issue: one deletes the commented out code, the other branch adds an explanation based on the reasons you gave.

**Comment by elsanussi-s-mneina** [comment]
I'm going to close this issue, since the question has been answered.
