### ISSUE TITLE
Add `memptyIfTrue/False` functions

### ISSUE THREAD

**Issue by vrom911** [kowainik/relude#293]
`memptyIfFalse` should return `mempty` when the given predicate is unsatisfied (`False`), otherwise, return the default given value:

```haskell
memptyIfFalse :: Monoid m => Bool -> m -> m
```

**Comment by srid** [comment]
Would this be a good addition?

```haskell
 (Monad m, Monoid a) => m Bool -> m a -> m a
```

**Comment by chshersh** [comment]
@srid That sounds like an interesting proposal :slightly_smiling_face: I don't mind adding new combinators to `relude`, since at least the names don't conflict with anything. However, when adding new functions, we need to consider multiple things, so I encourage you to open a separate issue to discuss new functions, possible names and types, and especially use-cases.
