### ISSUE TITLE
Add 'foldr1' to the 'Foldable1' typeclass

### ISSUE THREAD

**Issue by chshersh** [kowainik/relude#307]

**Comment by rektrex** [comment]
`foldr1` here should behave similar to `foldr` from the standard prelude, right?

**Comment by jgm** [comment]
`foldr1` from standard Prelude has type `(a -> a -> a) -> t a -> a`.
The idea is that if it's  nonempty structure, you don't need the "starting value" for the fold.

`foldr1` from relude has type `(a -> b -> b) -> b -> f a -> b`.  Note the extra parameter. Is this difference in type intended?

**Comment by chshersh** [comment]
@jgm Removing the default value would be nice indeed. However, it doesn't look trivial to do. I see, that even `semigroupoids` doesn't provide `foldr1`, and I don't see from Hoogle any library that provides safe `foldr1` with the nice type signature.

**Comment by Anton-Latukha** [comment]
Yeah, no base case is simple when:
```haskell
-- base
foldr  :: (a -> a -> a) -> t a -> a
```

But remove the base case for:
```haskell
-- base
foldr  :: (a -> b -> b) -> b -> t a -> b
-- relude
foldr1 :: (a -> b -> b) -> b -> t a -> b 
```

Is completely another thing.

AFAIK the base cases should not be removed. Everyone expects fold to have a function and then a base case. Base cases are free in provisioning and in the code performance. And giving base cases is a good FP practice. Base cases are essential for FP programming, Monoid empty, Nothing, `bool`, `maybe`, `either`, `fromMaybe` and etc. all give base cases first.

When to try to remove the base case too hard, the `base foldr1` is what comes out as a result, a one-sided non-general fold. and then people have this sort of discussion. To say like in the kindergarten: we see that the `base: foldr1` is one being weird here.

**Comment by jgm** [comment]
I guess that's my question exactly.  Why not have the signature
```
Foldable1 t => (a -> a -> a) -> t a -> a
```
Foldable1 is for nonempty structures; we have a way to get head and last, so why do we need to specify a base case?  This would make `foldr1` a drop-in replacement for Prelude's, more or less, instead of something completely different.  If you need the flexibility of
```
(a -> b -> b) -> b -> t a -> b
```
and don't mind specifying a base case, just use `foldr` which already looks like this.  Obviously there's something I'm missing.

**Comment by Anton-Latukha** [comment]
Because fold for non-empty structures if to take-out the base case would be in an imaginary world we imagine is:
```haskell
-- imaginary
(a -> b -> b) -> t a -> b
-- base
(a -> a -> a) -> t a -> a
-- relude
(a -> b -> b) -> b -> t a -> b
```

If to pick real one - it is the relude one. Because the `(a -> a -> a) -> t a -> a` is not practical.
It is much more practical to just give base case that is for free and have proper catamorphism.
Then to reduce what was for free to have a partial solution that constricts the implementation.

We actually participate in a years long epic discussion on why that `foldr1` was put there, it is a holly war, I used to read about it years ago, even before I learned Haskell properly.

**Comment by jgm** [comment]
I don't mean to engage in a holy war, but what confuses me is this.
NonEmpty is already an instance of Foldable, which has
```hs
foldr :: (a -> b -> b) -> b -> t a -> b
```
So what exactly is the difference between `foldr` and `foldr1` (with relude's type)?

**Comment by Anton-Latukha** [comment]
That `*1` naming used consistently. `foldr1` is `Foldable1`, which gives what `Foldable1` does - gives a guarantee that the structure is empty-safe. While `foldr` with `Foldable` does not gives that guarantee and allows non-total unsafe functions.

**Comment by jgm** [comment]
> While `foldr` with Foldable does not provide that guarantee and allows non-total unsafe functions.

`foldr` from the Foldable class is perfectly safe for empty structures, isn't it?  It's not a partial function.  Maybe I'm missing something, but I think you must have meant to be talking about `foldr1` from `Foldable`.  Yes, that function is not safe for empty structures.  So I would have expected `Foldable1` to provide a safe replacement `foldr1` that is restricted to nonempty structures but otherwise works like `foldr1` from `Foldable` (and has the same signature).  Instead, relude offers a function that has the same signature as `foldr` from `Foldable`, and (if I understand correctly) is equivalent to it (within a more limited domain of application) and thus redundant.  Wouldn't it be more useful to provide a safe `foldr1` with the original signature?  That would allow you to do something you can't already do with `foldr`.  I don't see how it helps to give us a function that just does what `foldr` already does but with a different name.

`foldr1` (with the original signature) is useful when there's no default base case, but you want to start with first element in the structure, whatever it happens to be.  I've seen cases like this; to achieve safety in these cases, I've just used `foldr` and a Maybe, but that's a bit awkward and I would have rather had a safe `foldr1` (with no base case) that is restricted to nonempty structures.

**Comment by Anton-Latukha** [comment]
Since `foldr` does not have NonEmpty boundary, one can use `(a -> b -> b)` on empty `t a` that is unsafe, the most simple "on the lap" example is to evaluate strictly - ` `\ xs acc -> acc <> head xs` or for that matter `\ xs acc -> f (acc <> head xs)`, or any function that implicitly uses root of the structure or the tail of it.

**Comment by Anton-Latukha** [comment]
> (within a more limited domain of application) and thus redundant.

This almost does not happen in Haskell, especially by thoughtful authors. In Haskell for "more limited domain of application" people often use words "specialized to", "more powerful", "optimized for". As if used properly when needed, special cases optimize better, for some cases `MonadPlus` for parsers is more powerful then `Alternative`, `Abelian` structure is much more performant then `Semigroup`, more restrictions, more properties - more implementation optimization possible. The weaker structures in most cases can be used, but frequently they work less efficiently. The best the most understandable example that I've seen is comparing `Associative` to `Associative & Commutative`, what is only `Associative` is strictly one-threaded sequential, the `Commutative` gives complete parallelism.

**Comment by Anton-Latukha** [comment]
> I would have rather had a safe foldr1 (with no base case) that is restricted to nonempty structures.

There are none such. NonEmpty structures always have the base case, that is what to do for `NonEmpty` value.

So if one `(a -> a -> a) -> t a -> a` one also needs to provide the base case, but now one needs to do it inside of the `(a -> a -> a)`, which is a limiting signature.
`relude: foldr1` allows the same thing, except that it does not require to pack base case into `(a -> a -> a)` requirements, the base case for `t a` now can be anything `b`, and catamorphism can be anything: `(a -> b -> b) -> b`.

Hence, `relude`s version is super to `base`s, and former called consistently, while the `(a -> a -> a) -> t a -> a` is a limiting fold that works only for some cases, it is still handy and useful, but needs other name.

**Comment by jgm** [comment]
> Since `foldr` is not NonEmpty typesafe, on empty `t a` the unsafe `(a -> b -> b)` can run on it. 

Sorry, I'm just not following.  Can you give an example where
```hs
foldr :: Foldable t => (a -> b -> b) -> b -> t a -> b
```
from `Foldable` blows up on an empty structure (`t a`)?  It's a totally defined function, is it not?  In what sense, exactly, is it unsafe to use on empty structures?
