### ISSUE TITLE
Issue? Little issue.

### ISSUE THREAD

**Issue by ARPL-c-63h** [kowainik/relude#308]
I have a little issue: Stop bugging me to ask for contributions each time I visit if you don't want any.
Before making suggestions I thought I would go over the documentation first. (README.md minor typos #300) 3 weeks was not enough for a review? I closed it a week ago, but you can still merge it if you want of course.

To quote your bot:
"There is no place for me here... I will choose the truth I like."

**Comment by chshersh** [comment]
We have organization-wide [contributing guide](https://github.com/kowainik/.github/blob/master/CONTRIBUTING.md), that describes the workflow of contributing to our projects. Specifically, it mentions discussing future work in the corresponding issues beforehand. In addition, we also have [Code of Conduct](https://github.com/kowainik/.github/blob/master/CODE_OF_CONDUCT.md) that tells what behaviour is inappropriate when we communicate with each other.

We are humans with personal lives, limited free time, energy and mental health. We spend our free time to make our projects better because we care about them. But we don't ask anyone specifically to spend their time contributing to @kowainik repositories if they don't want to. We're working in our own pace, prioritizing bugfixes.
