### ISSUE TITLE
use functional dependencies for StaticMap and DynamcMap

### ISSUE THREAD

**Issue by nalchevanidze** [kowainik/relude#333]
for `StaticMap`

https://github.com/kowainik/relude/blob/fe21aef8a7a4de061b2ffc69a74642db5b43a28e/src/Relude/Extra/Map.hs#L55-L61

did you considered functional dependencies?

```hs
class StaticMap key val t | t -> val , t -> key where
    size   :: t -> Int
    lookup :: key -> t -> Maybe val
    member :: key -> t -> Bool
```

we will have more control on k and v and  support newtype derivation.

```hs
newtype MyMap k v = MyMap {  unpackMyMap ::  HashMap k v }
  deriving newtype (StaticMap k v)
```

**Comment by nalchevanidze** [comment]
in adddition  you can support

```hs
import qualified Data.List as L

instance StaticMap k a [(k, a)] where
  size = L.length
  lookup = L.lookup
  member key = isJust . (lookup key)
```

**Comment by chshersh** [comment]
@nalchevanidze Thanks for your ideas! If the approach with FunDeps allows deriving typeclasses easily (especially using the `newtype` strategy), and the TypeFamilies approach doesn't, this seems like a worthy change :slightly_smiling_face:

**Comment by nalchevanidze** [comment]
additionally. you can bring generalised `lookup` back to `Prelude`, that will work for both: `[(k,a)]` and `Map k a`.

same can be used with also with typeCLass `One`

i can make PR for it. if you want

**Comment by chshersh** [comment]
@nalchevanidze I think `One` deserves a separate issue because it's exported by default, and I believe more people use `One` (at least I use `One` in almost every application, and I rarely reach to `Static/DynamicMap` typeclasses). Also, since `StaticMap` and `DynamicMap` are in `Extra` modules, introducing breaking changes to them is less dangerous :slightly_smiling_face:

Feel free to open a PR with changes to `StaticMap` and `DynamicMap`! And for for `One` we can create a separate issue, discuss it and raise awareness first, and implement in the release after the next one if it's worth it. Also, we will be able to see, how it works out with `StaticMap` and `DynamicMap` first :1st_place_medal: 

I'm not in favour of bringing generalized `lookup` back to `Prelude`. `StaticMap` and `DynamicMap` are in `Extra.*` modules, so it feels inconsistent to export `Extra` stuff by default. Also, I'm not quite satisfied with the `StaticMap` and `DynamicMap` approach. Ideally, generalized interfaces for containers should use Backpack:

* https://github.com/kowainik/containers-backpack

But Backpack is not mainstream yet, unfortunately... Though, it's possible that one day `StaticMap` and `DynamicMap` will be replaced by `containers-backpack` :thinking:

**Comment by vrom911** [comment]
@nalchevanidze could you please elaborate more on the advantages of having functional dependencies?

Your example of the newtype is also possible to do with the current solution:

```haskell
{-# LANGUAGE UndecidableInstances #-}

newtype MyMap k v = MyMap 
    { unpackMyMap :: HM.HashMap (k, Int) v 
    }
    deriving newtype (StaticMap)
```

And I haven't noticed issues with the control of the keys and values, and error messages also look quite informative. Can you please elaborate on what you have in mind? 🙂

**Comment by chshersh** [comment]
Closing as no action is needed at the moment.
