### ISSUE TITLE
Relude.Monad.Maybe combinator arguments are back-to-front ☹️

### ISSUE THREAD

**Issue by lrworth** [kowainik/relude#335]
For the sake of a discussion, in case someone else has similar thoughts in the future:

All the `when...` functions in Relude.Monad.Maybe might have better ergonomics if the arguments were flipped.

Compare:

```haskell
failWhenNothing :: MonadFail m => Maybe a -> m a
failWhenNothing = (`whenNothing` fail "Didn't work")
```

```haskell
logIfNothingHappened :: IO ()
logIfNothingHappened = doAThing >>= (`whenNothing` putStrLn "Nothing happened")
-- or
logIfNothingHappened = doAThing `whenNothingM` (putStrLn "Nothing happened")
```

I wish for
```haskell
whenNothing = flip maybe (const pass)
-- (And similar for the other when... functions)
```
so that we can
```haskell
failWhenNothing = whenNothing (fail "Didn't work")
logIfNothingHappened = doAThing >>= whenNothing (putStrLn "Nothing happened")
-- or
logIfNothingHappened = doAThing & whenNothingM (putStrLn "Nothing happened")
```

**Comment by lrworth** [comment]
Proof of concept here: https://github.com/lrworth/relude/commit/5c583cfe48efe394b2d7b24a3712592027a6c8fd

**Comment by chshersh** [comment]
> All the when... functions in Relude.Monad.Maybe might have better ergonomics if the arguments were flipped

Order of arguments of all `when*` functions is specified like this intentionally. For example, `whenNothing` function is supposed to be used like this:

```haskell
foo = do
    ...
    whenNothing cachedSessions $ do
        srv <- initServer
        createNewSession srv
```

If we flip arguments for such `when*` functions, it would be awkward to write such code.

I personally would rewrite the following code

```haskell
failWhenNothing = (`whenNothing` fail "Didn't work")
```

into a more explicit form:

```haskell
failWhenNothing m = whenNothing m (fail "Didn't work")
```

Relude is optimized for readability and maintainability instead of ability to write more pointfree code. Our goals is to be beginner-friendly.

**Comment by chshersh** [comment]
Closing this issue due to the reasons mentioned in my previous comment.
