### ISSUE TITLE
Text version of readMaybe

### ISSUE THREAD

**Issue by sullyj3** [kowainik/relude#339]
It would be nice to have a function `Show a => Text -> Maybe a`.
I often find myself writing `readMaybe . T.unpack`, which is a very minor papercut, but a papercut nonetheless. It takes me out of the nice world where I don't have to think about strings.

Are there any reasons not to include this function that I'm missing?

**Comment by chshersh** [comment]
Hi @sullyj3! We don't provide such a function, because it's very slow, and we don't want to encourage slow solutions. Relude goals are to be performant and to encourage best-practices, but a function of type `Read a => Text -> Maybe a` implemented as `readMaybe . T.unpack` is not performant, because:

1. Converting from `Text` to `String` is slow.
2. String is performance- and memory-wise inefficient data type.
3. Parsing via `Read` is slow.

So, if you want to parse `Text` directly and efficiently, you can use functions from the `Data.Text.Read` module from the `text` package:

* http://hackage.haskell.org/package/text-1.2.4.0/docs/Data-Text-Read.html#v:decimal

But those functions have common names and collide a lot. Moreover, there's no common standard typeclass (that can be also automatically derived by GHC) for parsing Haskell values from `Text`, so it's not possible to provide an efficient generic parsing function for `Text`.

**Comment by sullyj3** [comment]
Thanks for the info!
