### ISSUE TITLE
Please, explain the difference in use between `show` & `toText|toLText|toString`

### ISSUE THREAD

**Issue by Anton-Latukha** [kowainik/relude#374]
Both approaches do the same thing.
And the types tell that they do the same thing. `show` is 1 function being polymorphic on return type, and `toText|toLText|toString|encode/decodeUtf8` are polymorphic on the input type.

And both approaches have the type-class jump overhead on the face of them. So all and all taken at the face value - the both approaches look the same, except that instead of 5 functions, `show` allows using just 1.

But if one looks in the source code:
https://hackage.haskell.org/package/relude-1.0.0.1/docs/src/Relude.String.Conversion.html#show

`show` does `a -> String -> b` (meaning, does marshaling 2 times), which is obviously a very expensive operation.

These details of application seems to be in need of documentation.

**Comment by Anton-Latukha** [comment]
And I forgot about the escaping literals.

Good if it would be mentioned.

What are your thoughts?

**Comment by chshersh** [comment]
> Both approaches do the same thing.

This is not entirely true. `show` converts _any_ value to `String` using the provided `Show` instance (usually derived) and then converts this `String` to any type with the `IsString` instance for convenience, so you can return `String`, `Text` or even `Builder`. `show` is very slow but it's the only available way to get _some conversion of user-defined values to strings for free_.

`ToText` and others simply convert between various string types. You can check the following table to see the corresponding function for each two common string types in Haskell:

* http://hackage.haskell.org/package/relude-1.0.0.1/docs/Relude-String.html

Also, `show` changes the representation, while other conversion functions are idempotent:

```haskell
Prelude> show "string"
"\"string\""
Prelude> show $ show "string"
"\"\\\"string\\\"\""
Prelude> show $ show $ show "string"
"\"\\\"\\\\\\\"string\\\\\\\"\\\"\""
```

I'm not sure what needs to be documented because these functions are very different, and the `ToText` family of functions already has extensive documentation in a form of a conversion table and even custom type errors for invalid combinations.

If you check instances for the `ToText` typeclasses, you can see that they are implemented only for string types, while `Show` instance can be for almost any Haskell data type.

**Comment by Anton-Latukha** [comment]
Yep.

As I've put it:
> forgot about the escape literals difference.

This also seems like a nice case to make a small notes to guide people.

As `relude` gives prime-time to text data types refactroing. Previously `Show` differentiated the use, to not marshall into String - people were using Text functions directly, and `show` was used only for output things. To the point that topic opener forgot there is a difference between `pack/unpack` and `show`.

To clean-up the accumulated String technical debt, 1-st thing HNix migrated to `relude`.

I've seen the http://hackage.haskell.org/package/relude-1.0.0.1/docs/Relude-String.html right-away, but initially ignored it since its description is minimalistic and for thinking the following:

After/during migration to `relude` since the situation is changed - the barriers are no longer where they were, and the parametric `show` tempts to be used as an easy escape everywhere, and relearned that literals escaping compounding was the price, and that the marshaling happened anyway and twice.

That why I think that minimal note guard rails should be mentioned, in fact, that would be enough to guide migrations properly.

**Comment by chshersh** [comment]
I believe, the difference was explained.
