### ISSUE TITLE
Please, can: pass = pure mempty

### ISSUE THREAD

**Issue by Anton-Latukha** [kowainik/relude#379]
_(I looked through the threads, & at least the question is hard to search, since keywords are general)_

Overall `pure () == mempty` in itself, but bare `mempty` also has limited area of application (with function types).

`pass` & functions it is built on can be used on all (_iiuic_) >=2 layer monoid structures, if `pass = pure mempty`.

Interested in the question of why it was chosen/the current case restricting the functionality with `pass = pure ()`.

**Comment by chshersh** [comment]
This is a highly breaking change. If anything, this should be a new function. And it doesn't seem like something common. [According to Hoogle](https://hoogle.haskell.org/?hoogle=%28Applicative+f%2C+Monoid+m%29+%3D%3E+f+m&scope=set%3Astackage) there's no such function in any of the libraries. So I don't think it's good candidate for including in a standard library.

Also, writing `pure mempty` is not really that difficult compared to using `pass`. One might argue that `pure ()` is also not worth having a separate function `pass`. But that's historical reasons due to `relude` being a fork of `protolude` so `pass` probably won't go away.
