### ISSUE TITLE
Where is `Data.List.elemIndex` and friends?

### ISSUE THREAD

**Issue by kindaro** [kowainik/relude#384]
I tried to replace `Data.List` with `Relude.List` in a project I am working on and it turned out that `Relude.List` does not re-export `elemIndex`, `elemIndices`, `findIndex` and `findIndices`. It looks to me like these functions are safe. Can they be re-exported?

**Comment by chshersh** [comment]
Reexporting those functions probably will be a big breaking change if anyone uses their default versions for something like `Vector`. I'm not sure if we should encourage more usages of these functions on lists since they are not really efficient. They are not exported from `Prelude` so not exporting them from `Relude` sounds ok to me.

Currently, I'm opposed to reexporting them from `Relude`. I never needed those functions during the last 5 years of programming in Haskell. So I'm not sure if breaking code is worth reexporing those rarely needed functions.

**Comment by chshersh** [comment]
I'm closing this issue for now. If there's enough interest from many people in making such functions available by default, we could reconsider this decision and reexport them. But for now I'd prefer to keep with the **Minimalism** goal of `relude`.
