### ISSUE TITLE
Add a `Stream` type and make `iterate` return a stream.

### ISSUE THREAD

**Issue by kindaro** [kowainik/relude#386]
[`Stream`][1] is a handy type because it always has a head and a tail. It can also be dropped to `NonEmpty` and to the usual list free of charge. Unfolds without a base case are the class of functions that produce streams, `iterate` being the immediate example, and they could be typed as such.

I think this type would be a nice addition to `Relude`.

[1]: https://hackage.haskell.org/package/Stream/docs/Data-Stream.html

**Comment by chshersh** [comment]
The problem with adding something like a new type (e.g. `Stream`) is that it won't have all the instances as the original type. This will result in code duplication, and code reuse actually won't be possible since the `Stream` type in `relude` will be different from `Stream` type in another library. Since we don't want to depend on more non-boot libraries according to the goals of this project, reexporing `Stream` is not an option unless it happens to be on one the boot libraries.
