### ISSUE TITLE
base-noprelude is so 8.8.4

### ISSUE THREAD

**Issue by Anton-Latukha** [kowainik/relude#396]
Seems like in a while it would be reasonable to remove documentation on it, or mark/refer/remind about it as a former option for legacy GHC versions.

**Comment by chshersh** [comment]
`stack` still doesn't support mixins:

* https://github.com/commercialhaskell/stack/issues/5077

So `base-noprelude` is the only option to use custom preludes "easier" with this build tool, even if it requires using older GHC versions (and some people may still use older GHCs).

I'm okay with adding a small documentation note to the README and `src/Relude.hs` saying that this approach works only for GHC ≤ 8.8.4. Feel free to do this if you feel like it 👌🏻 

Ideally, someone else motivated enough could take take the maintenance of `base-noprelude` package and update it to all latest GHCs. But I personally don't have enough bandwidth for this.

**Comment by Anton-Latukha** [comment]
Pretty busy, because of war, 
I can not continue working on this.

**Comment by dcecile** [comment]
> maintenance of `base-noprelude` package

It doesn't seem sustainable for `base-noprelude` to be maintained outside of the GHC source code (where `base` [lives](https://gitlab.haskell.org/ghc/ghc/-/tree/master/libraries)).

Could we merge #435 or remove the doc section completely until a viable path for the library is found?

(I was setting up Stack with Relude today on GHC 9.4.6 and started setting up using this method before realising `base-noprelude` isn't maintained by GHC and hasn't had an update since 2018.)
