### ISSUE TITLE
Build failure in a released version when using an older version of 'containers'

### ISSUE THREAD

**Issue by chris-martin** [kowainik/relude#404]
I tried to build `relude-1.0.0.1` with `containers-0.5.7.1` using GHC 8.8.4 and got a compile error:

```
src/Relude/Nub.hs:62:1: error:
Error:     Could not load module ‘Data.Containers.ListUtils’
    It is a member of the hidden package ‘containers-0.6.2.1’.
    Perhaps you need to add ‘containers’ to the build-depends in your .cabal file.
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
62 | import qualified Data.Containers.ListUtils as Containers
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

This module was added in `containers-0.6.0.1`, so I'm thinking maybe it was a mistake for `containers-0.5.7.1` to be in bounds?

**Comment by chshersh** [comment]
[`containers` is a boot library](https://gitlab.haskell.org/ghc/ghc/-/wikis/commentary/libraries/version-history) so old GHC versions will use older versions of `containers` library. The earliest GHC version supported by Relude is 8.2.2 and this GHC versions ships with `containers-0.5.10.2`.

So, bumping up the lower bound from `0.5.7` to `0.5.10.2` is the correct thing to do nevertheless. But it won't solve your issue as `0.5.10.2` still doesn't have the `Data.Containers.ListUtils` module. However, I don't think this is a problem as Relude uses CPP to support older `containers` versions:

https://github.com/kowainik/relude/blob/fcb32257a37e34a48f70ddd55424394de4bb025c/src/Relude/Nub.hs#L80-L85

It's more surprising to me how you're using GHC with different versions of boot libraries instead of shipped one 🤔  But I guess it never was the expectation from `relude` to support "non-standard" combinations of GHC and boot library versions. I personally wasn't aware this is possible or supported.

You could try to bump up the lower bound for `containers` to `0.6` and see how the CI goes and whether it still works with old GHC versions. And if yes, CPP can be removed and the code will become cleaner 🧹 🙂

**Comment by sjakobi** [comment]
Even though `containers` is a boot library, `cabal` or `stack` aren't forced to use the version bundled with GHC.

Only the builtin subset of the boot libraries is non-upgradeable, e.g. `base`, `template-haskell` and the `ghc*` packages.

So the CPP on `ordNub` should refer to the `containers` version instead to the GHC version.
